import { v4 as uuid4 } from 'uuid'

export const coffees = [
  {
    id: uuid4(),
    image: 'coffees/expresso-tradicional.svg',
    label: ['tradicional'],
    title: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/expresso-americano.png',
    label: ['tradicional'],
    title: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/expresso-cremoso.png',
    label: ['tradicional'],
    title: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/expresso-gelado.png',
    label: ['tradicional', 'gelado'],
    title: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/cafe-com-leite.png',
    label: ['tradicional', 'com leite'],
    title: 'Café com Leie',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/latte.png',
    label: ['tradicional', 'com leite'],
    title: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/capuccino.png',
    label: ['tradicional', 'com leite'],
    title: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/macchiato.png',
    label: ['tradicional', 'com leite'],
    title: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/mocaccino.png',
    label: ['tradicional', 'com leite'],
    title: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/chocolate-quente.png',
    label: ['especial', 'com leite'],
    title: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/cubano.png',
    label: ['especial', 'alcóolico', 'gelado'],
    title: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/havaiano.png',
    label: ['especial'],
    title: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/arabe.png',
    label: ['especial'],
    title: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.99,
  },
  {
    id: uuid4(),
    image: '/coffees/irlandes.png',
    label: ['especial', 'alcóolico'],
    title: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.99,
  },
]
